### PR TITLE
Make a simpler API

### PR DESCRIPTION
**Pull request by abompard**
This is my experiment with a simpler API. The documentation update (and the commit message) should explain what changed and how to use the new one.

### CODE REVIEW

**Comment by abompard** [comment]
Since you've started working on client apps, I'd be interested in your opinion @StephenCoady .

**Comment by StephenCoady** [comment]
@abompard this looks great, much cleverer than what I had locally which was just manually wrapping everything in a class.

Would it make sense to also expose an exception to use for calls that fail? In the libraries I am using HTTP exceptions but it might make sense for that to come from this client as well?

**Comment by abompard** [comment]
That's what Bravado does currently, all failures are raised as an `bravado.exceptions.HTTPError` subclass. Since we are now basically hiding from users the fact that we use Bravado, it would indeed be useful to raise exceptions of our own so that we may swap Bravado for something else and not require users to change their code. I'll propose something along those lines, thanks for suggesting it.

**Comment by abompard** [comment]
I've added the error class @StephenCoady. What do you think?

**Pull request merged**
